### ISSUE TITLE
File is a CommonJS module; it may be converted to an ES6 module.ts(80001)

### ISSUE THREAD

**Issue by ykws** [mushahiroyuki/ndp2#1]
以下のコードに対して Visual Studio Code にて警告が表示されます。

https://github.com/mushahiroyuki/ndp2/blob/4e3a7fd602fd6d6f6054f6f3e71af02a71b83992/example/ch02/04_callback_unpredictable/test.js#L3

**Comment by ykws** [comment]
Visual Studio Code の Quick Fix では下記のように変更されます。

```javascript
import { readFile } from 'fs';
```

`node test` を実行するとエラーになります。

```shell
$ node test

import { readFile } from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:626:28)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
```
